USE `arblog-db`;

INSERT INTO `PROVIDERS` (`PROVIDER`)
VALUES
('BASIC'),
('GOOGLE');

INSERT INTO `PROFILES` (`PROFILE_NAME`,`BIRTH_DATE`, `CREATED_AT`,`UPDATED_AT`)
VALUES
('adriel15@','2000-09-15',NOW(),NOW());

INSERT INTO `AUTHORITIES` (`AUTHORITY`)
VALUES
('ADMIN'),
('WRITER'),
('READER');

INSERT INTO `USERS` (`USERNAME`,`PASSWORD`,`EMAIL`,`ENABLED`,`CREATED_AT`,`UPDATED_AT`,`PROVIDER_ID`,`PROFILE_ID`)
VALUES
('rosario123','$2a$10$4r9f2K5RLGByAIYknDU3GuyGYrrHnoRHaB5vikmu4JDS2YPBv85SO','adriel15@gmail.com',1,NOW(),NOW(),1,1);

INSERT INTO `USERS_AUTHORITIES` (`USER_ID`,`AUTHORITY_ID`)
VALUES
(1,1),
(1,2),
(1,3);