CREATE DATABASE IF NOT EXISTS `arblog-db`;

USE `arblog-db`;

DROP TABLE IF EXISTS `USERS_AUTHORITIES`;
DROP TABLE IF EXISTS `AUTHORITIES`;
DROP TABLE IF EXISTS `USERS`;
DROP TABLE IF EXISTS `PROVIDERS`;
DROP TABLE IF EXISTS `PROFILES`;

CREATE TABLE `PROFILES` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `PROFILE_NAME` VARCHAR(200) DEFAULT NULL,
    `BIRTH_DATE` DATE DEFAULT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `CREATED_BY` VARCHAR(320) DEFAULT NULL,
    `UPDATED_BY` VARCHAR(320) DEFAULT NULL,

    KEY `CREATED_AT_IDX` (`CREATED_AT`),
    KEY `UPDATED_AT_IDX` (`UPDATED_AT`),
    KEY `UPDATED_BY_IDX` (`UPDATED_BY`),
    KEY `CREATED_BY_IDX` (`CREATED_BY`),

    PRIMARY KEY (`ID`)
);

CREATE TABLE `PROVIDERS` (
    `ID` TINYINT NOT NULL AUTO_INCREMENT,
    `PROVIDER` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `USERS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(100) DEFAULT NULL,
    `PASSWORD` VARCHAR(300) DEFAULT NULL,
    `EMAIL` VARCHAR(320) NOT NULL,
    `ENABLED` TINYINT(1) NOT NULL,
    `PROVIDER_UID` VARCHAR(300) DEFAULT NULL,
    `PROVIDER_ID` TINYINT NOT NULL,
    `PROFILE_ID` BIGINT NOT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME DEFAULT NULL,
    `CREATED_BY` VARCHAR(320) DEFAULT NULL,
    `UPDATED_BY` VARCHAR(320) DEFAULT NULL,

    PRIMARY KEY (`ID`),

    UNIQUE KEY `USERNAME_UNIQUE_KEY` (`USERNAME`),
    UNIQUE KEY `EMAIL_UNIQUE_KEY` (`EMAIL`),
    UNIQUE KEY `PROVIDER_UID_UNIQUE_KEY` (`PROVIDER_UID`),
    UNIQUE KEY `PROFILE_ID_UNIQUE_KEY` (`PROFILE_ID`),

    KEY `PROVIDER_ID_IDX` (`PROVIDER_ID`),
    KEY `CREATED_AT_IDX` (`CREATED_AT`),
    KEY `UPDATED_AT_IDX` (`UPDATED_AT`),
    KEY `UPDATED_BY_IDX` (`UPDATED_BY`),
    KEY `CREATED_BY_IDX` (`CREATED_BY`),

    CONSTRAINT `FK_PROVIDER` FOREIGN KEY (`PROVIDER_ID`) REFERENCES `PROVIDERS` (`ID`),
    CONSTRAINT `FK_PROFILE` FOREIGN KEY (`PROFILE_ID`) REFERENCES `PROFILES` (`ID`)

);

CREATE TABLE `AUTHORITIES` (
    `ID` TINYINT NOT NULL AUTO_INCREMENT,
    `AUTHORITY` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `USERS_AUTHORITIES` (
    `USER_ID` BIGINT NOT NULL,
    `AUTHORITY_ID` TINYINT NOT NULL,

    PRIMARY KEY (`USER_ID`,`AUTHORITY_ID`),

    CONSTRAINT `FK_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`),
    CONSTRAINT `FK_AUTHORITY` FOREIGN KEY (`AUTHORITY_ID`) REFERENCES `AUTHORITIES` (`ID`)
);